spring:
  application:
    name: eureka-server
server:
  port: 8761

eureka:
  client:
    # by default these are true, but we don't want this app to register on eureka of course
    fetch-registry: false
    register-with-eureka: false
